baseurl = "https://example.org/"
languageCode = "en-us"
title = "Miles | 小语种学习交流平台"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Miles"
	description = "小语种学习交流平台 | 一款可以养鸡的学习app"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "M i l e s | 小 语 种 学 习 之 旅"

		[params.navigation.links]
			about     = "关于"
			services  = "服务"
			portfolio = "活动"
			contact   = "联系方式"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Miles"
		subtitle   = """[一带一路](//zh.wikipedia.org/zh-hans/一带一路) &nbsp;下的小语种学习软件"""
		buttonText = "了解更多"


	# About section
	[params.about]
		headline    = "Miles 与众不同"
		description = """[Miles](//google.com) &nbsp;是一款可以养鸡的学习软件。它不仅仅是一个个性化小语种学习分享交流平台，也可以说是一个游戏软件。通过
		在学习软件中融入游戏化因素，为小语种学习者提供一个学习监督激励、经验分享、学习问答平台，结合虚拟宠物系统，带来新颖的小语种学习体验。"""
		buttonText  = "立即下载"


	# Service section
	[params.services]
		headline = "软件特色"
        # icon url:https://fontawesome.com/v4.7.0/icons/

        [[params.services.list]]
            icon = "fa-clock-o"
            title = "番茄钟学习法"
            description = "番茄工作法极大地提高了工作的效率，还会有意想不到的成就感。"

        [[params.services.list]]
			icon = "fa-group"
			title = "多人监督学习"
			description = "可随机匹配正在进行小语种学习的用户一起学习，互相监督督促。"

		# [[params.services.list]]
        #     icon = "fa-comments"
        #     title = "多人情景学习"
        #     description = "剧本杀模式，通过多人角色扮演，让用户声临其境地学习小语种。"

        # [[params.services.list]]
        #     icon = "fa-tags"
        #     title = "学习记录板块"
        #     description = "用户可以记录自己的学习动态，促进激励自己与他人的共同学习。"

        [[params.services.list]]
            icon = "fa-share-alt"
            title = "资料分享板块"
            description = "用户可以上传个人呢学习资料，与其他小语种学习者共享学习资料。"

        [[params.services.list]]
            icon = "fa-question"
            title = "学习问答板块"
            description = "学习问答模块提供用户问答交流的平台，鼓励用户交流与分享经验。"
        
        # [[params.services.list]]
        #     icon = "fa-bug"
        #     title = "宠物成长系统"
        #     description = "用户的学习时长将会转换成虚拟宠物走过的里程数，激励小语种学习者。"
        
        # [[params.services.list]]
        #     icon = "fa-gift"
        #     title = "宠物服饰系统"
        #     description = "通过以上方式获得的虚拟货币可以为您的爱宠购买虚拟装饰服饰。"
    
    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "关闭"

    # Aside section
	[params.aside]
		headline = "开始您小语种之旅，别错过Miles"

		[params.aside.button]
			text = "立即下载"
			link = "//www.weekbin.xyz"

	# Contact section
	[params.contact]
		headline = "联系我们"
		description = "如果您对我们的项目感兴趣或者在使用中遇到了问题，请联系我们，我们会尽快给您答复！"
		phone = "13585900697"
		email = "864348876@qq.com"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
